# Usa una imagen oficial de Node.js como imagen base
FROM node:16-alpine

# Define el directorio de trabajo como /app
WORKDIR /app

# Instala Git
RUN apk add --no-cache git

# Clona el repositorio de Git
RUN git clone https://github.com/username/my-angular-app.git .

# Instala las dependencias
RUN npm install

# Construye la aplicación
RUN npm run build --prod

# Usa la imagen de Nginx como imagen base
FROM nginx:alpine

# Copia los archivos de construcción de la aplicación a la imagen de Nginx
COPY --from=0 /app/dist/my-angular-app /usr/share/nginx/html

# Copia el archivo de configuración de Nginx a la imagen
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expone el puerto 80
EXPOSE 80

# Inicia el servidor Nginx
CMD ["nginx", "-g", "daemon off;"]
