version: '3.8'
services:
  mongo:
    image: mongo:6.0.8
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend-network

  api:
    build: ./simpleAPI
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/hitcounter
    depends_on:
      - mongo
    networks:
      - backend-network

  frontend:
    build: ./simpleReactApp
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - api
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongodb_data:
