version: '3.8'
services:
  web:
    build: ./web
    environment:
      - VIRTUAL_HOST=example.com,www.example.com
  api:
    build: ./api
    environment:
      - VIRTUAL_HOST=api.example.com
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api

